### PR TITLE
Prevent crash - stays py3 unready on Feed

### PR DESCRIPTION
**Pull request by ghost**
[Prevent crash](https://www.opena.tv/plugins/6240-specialjump-plugin-zum-schnellen-manuellen-ueberspringen-von-werbung-und-mehr-post517955.html#post517955)

### CODE REVIEW

**Comment by jbleyel** [comment]
This is already fixed.

https://github.com/openatv/SpecialJump/blob/python3/usr/lib/enigma2/python/Plugins/Extensions/SpecialJump/plugin.py#L1035

**Comment by ghost** [comment]
I didn't want close.
I didn't saw the warning on delete my fork.

**Comment by Fischreiher** [comment]
Fixed in python3 branch, see jbleyel's comment above.
Is a fix mandatory for the master (python2) branch?

**Comment by jbleyel** [comment]
The master looks ok because we have not changed atv 6.4.

**Comment by Fischreiher** [comment]
Thank you! Case closed.

**Pull request closed without merging**
